### ISSUE TITLE
Cant install aw

### ISSUE THREAD

**Issue by RiteshChepuri** [joshmedeski/aw#6]
Cloning the aw repo in .config isn't installing aw in Linux.

- [ ] To even run the run script in bin folder we need node modules to installed.
- [ ] Include npm install in Readme.

**Comment by joshmedeski** [comment]
I intend on revisiting this program one day, but it is still in very early ALPHA development.

If you want to update the README with a PR I'm happy to merge it. But I will most likely be rewriting this later this year in a different language (possibly golang).
